[package]
name = "code_gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
path = "src/generator.rs"

[[bin]]
path = "src/bin.rs"
name = "code_gen"
